# Node.js version major release (NodeSource installer)
node_major_version: "22"

# List of packages required before Node.js install
base_packages:
  - git
  - curl
  - build-essential

# Whether to install yarn globally
install_yarn: false