all:
  hosts:
    minio:
      ansible_host: "{{ minio_host | default('192.168.1.100') }}"
      ansible_user: "{{ ansible_user | default('deploy') }}"
      ansible_become: yes
      ansible_become_method: sudo
      ansible_python_interpreter: /usr/bin/python3
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
